# Angular - Frontend - CD

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'joachimveulemans/license-plate-reader'
    command: 'buildAndPush'
    Dockerfile: 'frontend/Dockerfile'
    buildContext: 'frontend'
    tags: 'frontend'
