name: Python-Backend

on:
  pull_request:
    branches:
    - master

jobs:
  Build-Docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build ./backend/ --tag joachimveulemans-build-test:$(date +%s)